import { Language, Translation } from './types';

export const TRANSLATIONS: Translation = {
  appTitle: { en: "Muawiya Editing Toolkit", ur: "معاویہ ایڈیٹنگ ٹول کٹ" },
  home: { en: "Home", ur: "ہوم" },
  projects: { en: "Projects", ur: "پروجیکٹس" },
  editor: { en: "Editor", ur: "ایڈیٹر" },
  settings: { en: "Settings", ur: "سیٹنگز" },
  apiSetup: { en: "API Setup", ur: "API سیٹ اپ" },
  about: { en: "About", ur: "میرے بارے میں" },
  newProject: { en: "New Project", ur: "نیا پروجیکٹ" },
  recentProjects: { en: "Recent Projects", ur: "حالیہ پروجیکٹس" },
  untitled: { en: "Untitled", ur: "بلا عنوان" },
  language: { en: "Language", ur: "زبان" },
  theme: { en: "Theme", ur: "تھیم" },
  light: { en: "Light", ur: "لائٹ" },
  dark: { en: "Dark", ur: "ڈارک" },
  system: { en: "System", ur: "سسٹم" },
  save: { en: "Save", ur: "محفوظ کریں" },
  export: { en: "Export", ur: "ایکسپورٹ" },
  addText: { en: "Add Text", ur: "ٹیکسٹ شامل کریں" },
  addImage: { en: "Add Image", ur: "تصویر شامل کریں" },
  addShape: { en: "Add Shape", ur: "شکل شامل کریں" },
  generateBg: { en: "Generate BG", ur: "پس منظر بنائیں" },
  layers: { en: "Layers", ur: "لیئرز" },
  properties: { en: "Properties", ur: "خصوصیات" },
  delete: { en: "Delete", ur: "حذف کریں" },
  undo: { en: "Undo", ur: "واپس" },
  redo: { en: "Redo", ur: "آگے" },
  width: { en: "Width", ur: "چوڑائی" },
  height: { en: "Height", ur: "اونچائی" },
  color: { en: "Color", ur: "رنگ" },
  font: { en: "Font", ur: "فونٹ" },
  uploadImage: { en: "Upload Image", ur: "تصویر اپ لوڈ کریں" },
  apiKeyInstructions: { en: "Enter your Google Gemini API Key. This is required for AI features.", ur: "اپنی گوگل جیمنی API کلید درج کریں۔ یہ AI خصوصیات کے لیے ضروری ہے۔" },
  saveKey: { en: "Save Key", ur: "کلید محفوظ کریں" },
  developer: { en: "Developer", ur: "ڈویلپر" },
  contact: { en: "Contact", ur: "رابطہ" },
  promptPlaceholder: { en: "Describe the image background...", ur: "پس منظر کی تفصیل لکھیں..." },
  generating: { en: "Generating...", ur: "تیار ہو رہا ہے..." },
  success: { en: "Success", ur: "کامیاب" },
  error: { en: "Error", ur: "خرابی" },
  opacity: { en: "Opacity", ur: "شفافیت" },
  size: { en: "Size", ur: "سائز" },
  bringFront: { en: "Bring to Front", ur: "سب سے اوپر لائیں" },
  sendBack: { en: "Send to Back", ur: "سب سے نیچے بھیجیں" },
  lock: { en: "Lock", ur: "لاک" },
  unlock: { en: "Unlock", ur: "ان لاک" },
  openEditor: { en: "Open Editor", ur: "ایڈیٹر کھولیں" },
  continueProject: { en: "Continue Project", ur: "پروجیکٹ جاری رکھیں" },
  create: {en: "Create", ur: "بنائیں"},
  startBlank: {en: "Start Blank", ur: "خالی شروع کریں"},
  describeProject: {en: "Describe your poster idea...", ur: "اپنے پوسٹر کا آئیڈیا لکھیں..."},
  aiGenerate: {en: "AI Generate", ur: "AI جنریٹ"},
  rename: {en: "Rename", ur: "نام تبدیل"},
  exportZip: {en: "Export Project (ZIP)", ur: "پروجیکٹ ایکسپورٹ (ZIP)"},
  importProject: {en: "Import Project", ur: "پروجیکٹ امپورٹ"},
  selectImage: {en: "Select Image", ur: "تصویر منتخب کریں"},
  generatedHistory: {en: "Generated History", ur: "جنریٹڈ ہسٹری"},
  noProject: {en: "No Project Open", ur: "کوئی پروجیکٹ نہیں کھلا"},
  startNew: {en: "Start New Project", ur: "نیا پروجیکٹ شروع کریں"},
  transform: { en: "Transform", ur: "ٹرانسفارم" },
  moveSpeed: { en: "Move Speed", ur: "حرکت کی رفتار" },
  replace: { en: "Replace", ur: "تبدیل کریں" },
  gallery: { en: "Gallery", ur: "گیلری" },
  content: { en: "Content", ur: "مواد" },
  style: { en: "Style", ur: "اسٹائل" },
  rotate: { en: "Rotate", ur: "گھمائیں" },
  position: { en: "Position", ur: "پوزیشن" },
  apiKeySaved: { en: "API Key Saved", ur: "API کلید محفوظ ہے" },
  edit: { en: "Edit", ur: "ترمیم" },
  placeholderImage: { en: "Image Placeholder", ur: "تصویر کی جگہ" },
};

export const FONTS = [
  { name: 'Inter', value: 'Inter, sans-serif', label: 'Inter (English)' },
  { name: 'Arial', value: 'Arial, sans-serif', label: 'Arial' },
  { name: 'Mehr Nastaliq', value: '"Noto Nastaliq Urdu", serif', label: 'Mehr Nastaliq (Urdu)' },
  { name: 'Amiri', value: '"Amiri", serif', label: 'Amiri (Arabic)' },
  { name: 'Scheherazade', value: '"Scheherazade New", serif', label: 'Scheherazade (Arabic)' },
];

export const SHAPES = [
  { type: 'rectangle', label: 'Rectangle' },
  { type: 'circle', label: 'Circle' },
  { type: 'triangle', label: 'Triangle' },
  { type: 'star', label: 'Star' },
];